### ISSUE TITLE
Add "Yikes take" to Utena video transcript

### ISSUE THREAD

**Issue by Beckyhop13** [tustin2121/James_Somerton_Transcripts#9]
> Especially towards the end of the second arc, discourse around growing up takes a a central role as a driving theme. (😏) And then suddenly we get the third season and everyone is in cars and their shirts are flying off and... Is Akio fucking Touga?! Not that Akio doesn't have these chaotic Bi vibes but... what does a casual approach to sexuality have to do with cars?

I think this should be marked as a "yikes" take because Touga is a highschooler and Akio is an adult, so painting this as "chaotic Bi vibes" and "a casual approach to sexuality" is super gross

**Comment by tustin2121** [comment]
You are right. Especially after James made it a point to highlight that the characters are in middle and high school. Adding this now.
