### ISSUE TITLE
[GayPanicDef] The History of Gay Panic

### ISSUE THREAD

**Issue by tustin2121** [tustin2121/James_Somerton_Transcripts#93]
- [ ] Create Transcript
- [ ] Add Sources
- [ ] Highlight Sources

**Comment by lesepr** [comment]
@tustin2121 Found multiple sources for this video. I'm about 75-80% through the transcript. Do I add the sources here or create a separate issue?

**Comment by tustin2121** [comment]
Add them to a new issue, so it can be tracked separately. These video issues are to help us see how far along we are on the whole project, and I've lost sources before that get stuck into the comments on them. Thanks for your help!
